# 导航菜单
[[main]]
    identifier = "home"
    name = "主页"
    url = "/"
    weight = 10
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"  # 确保路径指向 content/page/archives/
    weight = 30
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"    # 确保路径指向 content/page/search/
    weight = 40
    [main.params]
        icon = "search"

[[main]]
    identifier = "about"
    name = "关于"
    url = "/about/"     # 确保路径指向 content/page/about/
    weight = 20
    [[main.params]]
        icon = "user"
# 社交链接
[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/AnCs-Lan"
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    [social.params]
        icon = "rss"

[[social]]
    identifier = "mail"
    name = "E-Mail"
    url = "mailto:AnCs-Lan@example.com"
    [social.params]
        icon = "mail"
